spring-i18n-example/src/main/java/com/javachen/domain/User.java
package com.javachen.domain;

import org.apache.commons.lang3.StringUtils;

import java.util.Calendar;

public class User {

	private String name;
	private String firstName;
	private Calendar birthDay;
	private boolean isMale;
	
	public User(String name, String firstName, Calendar birthDay, boolean isMale) {
		setName(name);
		setFirstName(firstName);
		setBirthDay(birthDay);
		setMale(isMale);
	}
	
	public User() { }
	
	public String getName() {
		return name;
	}
	
	public void setName(String name) {
		this.name = name;
	}
	
	public String getFirstName() {
		return firstName;
	}
	
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}
	
	public Calendar getBirthDay() {
		return birthDay;
	}
	
	public void setBirthDay(Calendar birthDay) {
		this.birthDay = birthDay;
	}
	
	public boolean isMale() {
		return isMale;
	}
	
	public void setMale(boolean isMale) {
		this.isMale = isMale;
	}
	
	@Override
	public String toString() {
		return StringUtils.join(getFirstName(), " ", getName());
	}
}

spring-i18n-example/src/main/java/com/javachen/controller/MainController.java
package com.javachen.controller;

import com.javachen.domain.User;
import com.javachen.locale.LocaleStorage;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.support.RequestContextUtils;

import javax.servlet.http.HttpServletRequest;
import java.util.GregorianCalendar;

@Controller
public class MainController {
	
	@Autowired
	private LocaleStorage storage;

	@RequestMapping(value = "/index.html")
	public String getIndex(ModelMap model) {
		model.addAttribute("user", new User("Gates", "Bill",
				new GregorianCalendar(1955, 9, 28), true));
		return "index";
	}
	
	@RequestMapping(value = "/test.html")
	public String getTest(HttpServletRequest request, ModelMap model) {
		model.addAttribute("test", storage.get(RequestContextUtils.getLocale(request), "label.birthday"));
		return "test";
	}
}

spring-i18n-example/src/main/webapp/WEB-INF/views/index.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>
<html>
<head>
	<meta charset="utf-8">
</head>
<body>
	<h2>${user}</h2>
	<ul>
		<li><spring:message code="label.birthday" />: <fmt:formatDate value="${user.birthDay.time}" type="date" dateStyle="short" /></li>
		<li><spring:message code="label.gender" />:
			<c:choose>
				<c:when test="${user.male}"><spring:message code="label.male" /></c:when>
				<c:otherwise><spring:message code="label.female" /></c:otherwise>
			</c:choose>
		</li>
	</ul>
	<ul>
		<li><a href="?lang=zh">Chinese</a></li>
		<li><a href="?lang=en">English</a></li>
		<li><a href="?lang=nl">Nederlands</a></li>
	</ul>
</body>
</html>

spring-i18n-example/src/main/webapp/WEB-INF/views/test.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>
<html>
<head>
	<meta charset="utf-8">
</head>
<body>
	<h2>${test}</h2>
	<ul>
		<li><a href="?lang=zh">Chinese</a></li>
		<li><a href="?lang=en">English</a></li>
		<li><a href="?lang=nl">Nederlands</a></li>
	</ul>
</body>
</html>